name = input('Enter Your Name : ')
city = input('Enter Your City :')
fav_food = input('Enter your Fav Food :')
vehicle = input('Enter the type of commuting Vehicle')
fav_color = input('Enter fav color')
hobby = input('Enter hobby')
pet = input('Enter the type of pet you own')
fav_drink = input('Enter the type of drink you usually prefer')
fav_movie = input('What kind of Movie Do You usually watch')
fav_sport = input('What type of sport U usually play')
print("!!!!!   INFO   !!!!!")
print(f'Name : {name}')
print(f'City : {city}')
print(f'Favourite Food : {fav_food}')
print(f'Type of commuting vehicle : {vehicle}')
print(f' Fav Color = {fav_color}')
print(f'Hobby : {hobby}')
print(f'Type of Pet {pet}')
print(f'Fav Drink : {fav_drink}')
print(f'Fav Movie : {fav_movie}')
print(f'Fav Sport : {fav_sport}')

